travis:
  secure:
    BINSTAR_TOKEN: ax7bf5f+Gg/I5sCZs2NGsqz3Ga8tl20qmEVgZlfSR6cG3jM+7zjZEoBpASwz+d4jnlaDfmTBgWagbL5CuFSuvzTLBWHkbW+1wqmKvdYV/Dg+7Sm6eChasoVmGtXSlya0HTaGRC6Fqp129LA5KtNRxgTPRLyuss5GiL4UnoMkmH6obFu656SeNHNFowDPTOjuEOjHRYyUHn3cgdfAk9jatwBb0PAWSRv1/gb4dt71grYQKZhR4wdT/2mC1xoKIL2TP+4zdn+TxYvbji2tgyhyz+Mi81ZbbRsldeu6c19+ejGufBRFzMleaxDr3wNSG9W62hEOffCRHGWqHnG5jNzbJ6Jro9maqLLceIpglhiyvRdT+zGL/3PZo1Tu8dpItuZYFUPAgE2ACjlUBSrBCd46iqVpBvBVp4Xqk6K/qQqym+k5gcsAp/GddWYiiB0eevqM3Oq7HimI/ITJj8msFRpM6PIICwNUDG65hIffopVESMmJmQyOnGMOe/B33Bvmw26eCrmCgeLOvbeq51NoEkCT1ZDqjj3VYMo2OLHnUk1MPDNpXoVV8o9WMI/7g+DVDl9kJhH6d0GRTG7sRDCjlzdBntUa3touZvFM0SccoFsUxEqCFgiOaTmBqUlEsA1DkrDzWAU+UOTBVldrq4bh/02YmgZ350tKFbxHL5q9b4lZwQc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
